### ISSUE TITLE
Follow PEP8

### ISSUE THREAD

**Issue by morsik** [cloudOver/PyCore#1]
Module name should be `pycore` instead of `pyCore`. Or maybe better just `cloudover`?

**Comment by cloudOver** [comment]
Thanks for sugestion. I'll change it in next release. 

Now, I'm considering moving cloudover's packages into PyPi repository. Probably most of packages will be moved into one "cloudover" package (with lowercase o :)

**Comment by cloudOver** [comment]
Module was renamed. Since 15.12 it is pycore
